force-app/main/default/objects/Parent_Object__c/Parent_Object__c.object-meta.xml
<CustomObject>
    <label>Parent Object</label>
    <nameField>
        <label>Parent Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parent Object</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent_Object__c/fields/My_Text__c.field-meta.xml
<CustomField>
    <fullName>My_Text__c</fullName>
    <label>My Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ParentTriggerHandler.cls
public class ParentTriggerHandler {
    public static void beforeUpdate(List<Parent_Object__c> newList, Map<Id,Parent_Object__c> oldMap){
        for(Parent_Object__c op: newList){
            op.My_Text__c='14';
        }
    }
    public static void afterUpdate(List<Parent_Object__c> newList, Map<Id,Parent_Object__c> oldMap){
       for(Parent_Object__c op: newList){
            System.debug(op.My_Text__c);
        }
    }
}