force-app/main/default/objects/KQClockLog__c/KQClockLog__c.object-meta.xml
<CustomObject>
    <label>KQClockLog</label>
    <nameField>
        <displayFormat>KQ-{0000000000}</displayFormat>
        <label>KQClockLogs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KQClockLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KQClockLog__c/fields/KRS__c.field-meta.xml
<CustomField>
    <fullName>KRS__c</fullName>
    <label>KRS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/KQClock.cls
public with sharing class KQClock {
    public static Long startTime;
    public static Long stopTime;

    public static Long startTimer(){
        startTime = DateTime.now().getTime();
        return startTime;
    }

    public static Long stopTimer(){
        stopTime = DateTime.now().getTime();
        return stopTime;
    }

    public static Long getKRS(){
        return stopTime - startTime;
    }
    @future
    public static void logTime(String key,Long krs){
        KQClockLog__c kqlog = new KQClockLog__c();
        kqlog.Key__c = key;
        Kqlog.KRS__c = krs;
        insert kqlog;
    }
}