force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Primary_Income_Source__c.field-meta.xml
<CustomField>
    <fullName>Primary_Income_Source__c</fullName>
    <formula>&apos;7&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Income Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOS_PQ_Income_Source_Automation_Setting__mdt/LOS_PQ_Income_Source_Automation_Setting__mdt.object-meta.xml
<CustomObject>
    <label>LOS PQ Income Source Automation Setting</label>
    <pluralLabel>LOS PQ Income Source Automation Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/LOS_PQ_Income_Source_Automation_Setting__mdt/fields/Primary_Source_of_Income_Ref_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_Source_of_Income_Ref_Code__c</fullName>
    <label>Primary Source of Income Ref Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOS_PQ_Income_Source_Automation_Setting__mdt/fields/Secondary_Source_of_Income_Ref_Code__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Source_of_Income_Ref_Code__c</fullName>
    <label>Secondary Source of Income Ref Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/Personal_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Personal Questionnaire</label>
    <nameField>
        <label>Personal Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Annual_Income_from_1099__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income_from_1099__c</fullName>
    <label>Self-Employed, Contracted or Freelance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Annual_Income_from_Employment__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income_from_Employment__c</fullName>
    <label>Employment Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Annual_Income_from_Pension__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income_from_Pension__c</fullName>
    <label>Pension</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Personal Questionnaires</relationshipLabel>
    <relationshipName>Personal_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Primary_Income_Source__c.field-meta.xml
<CustomField>
    <fullName>Primary_Income_Source__c</fullName>
    <label>Primary Income Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_Of_Income</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Secondary_Income_Source__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Income_Source__c</fullName>
    <label>Secondary Income Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_Of_Income</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Questionnaire_Revamp_Setting__c/Questionnaire_Revamp_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Questionnaire Revamp Setting</label>
</CustomObject>

force-app/main/default/objects/Questionnaire_Revamp_Setting__c/fields/Enable_Income_Breakdown__c.field-meta.xml
<CustomField>
    <fullName>Enable_Income_Breakdown__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Income Breakdown</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LosPersonalQuestionnaireIncomeSourceTest.cls
/**
 * @File Name : LosPersonalQuestionnaireIncomeSourceTest.cls
 * @Description : TECH-86358, This class contains unit tests for validating the behavior of
 * LosPersonalQuestionnaireIncomeSource Apex class
 * @Author : Kanak
 * @Last Modified By :
 * @Last Modified On : March 28, 2025
 * @Modification Log :
 *==============================================================================
 * Ver | Date | Author | Modification
 *==============================================================================
 * 1.0 | March 28, 2025 | Kanak  | Initial Version
 **/

@isTest
private class LosPersonalQuestionnaireIncomeSourceTest {
    
    @testSetup
    static void setupTestData(){
        //Create Questionnaire_Revamp_Setting__c Custom Setting record for current user
        Questionnaire_Revamp_Setting__c qrs = new Questionnaire_Revamp_Setting__c();
        qrs.Enable_Income_Breakdown__c = true;
        qrs.SetupOwnerId=UserInfo.getUserId();
        insert qrs;
    }
    
    
    @isTest
    static void unitTest1IncomeSourceAutomationOnPQInsertion(){
        //Create Application
        Application__c app = new Application__c();
        insert app;
        
        //Create Personal Questionnaire Record
        Personal_Questionnaire__c pq = new Personal_Questionnaire__c();
        pq.Name='Test';
        pq.Application__c=app.Id;
        pq.Annual_Income_from_Employment__c = 100;
        insert pq;
        
        //Get LOS_PQ_Income_Source_Automation_Setting__mdt Metadata Records
        Map<String, LOS_PQ_Income_Source_Automation_Setting__mdt> automationSettings = LOS_PQ_Income_Source_Automation_Setting__mdt.getAll();
        
        //Validation LOS_PQ_Income_Source_Automation_Setting__mdt Metadata Records
        Map<String, LOS_PQ_Income_Source_Automation_Setting__mdt> validAutomationSettings = LosPersonalQuestionnaireIncomeSource.validateAutomationSettings(automationSettings);
        
        //Get Personal Questionnaire Record after creation
        Personal_Questionnaire__c pqRecord = [SELECT Id, Primary_Income_Source__c FROM Personal_Questionnaire__c WHERE Id = :pq.Id];
        
        /**
         * Validate Test Result
         * Expected: Primary_Income_Source__c = 'Annual_Income_from_Employment__c' Ref Code
         */
        
        //Assert Primary_Income_Source__c value on PQ Record
        System.assertEquals(validAutomationSettings.get('Annual_Income_from_Employment__c').Primary_Source_of_Income_Ref_Code__c,
        pqRecord.Primary_Income_Source__c,
        'Primary_Income_Source__c is not populated as expected On PQ Record. Please validate LOS_PQ_Income_Source_Automation_Setting__mdt custom metadata and LosPersonalQuestionnaireIncomeSource class');
    }
    
    @isTest
    static void unitTest2IncomeSourceAutomationOnPQUpdation(){
        //Create Application Record
        Application__c app = new Application__c();
        insert app;
        
        //Create Personal Questionnaire Record
        Personal_Questionnaire__c pq = new Personal_Questionnaire__c();
        pq.Name='Test';
        pq.Application__c=app.Id;
        insert pq;
        
        //Update Income Field on PQ Record on the same record as inserted above
        Personal_Questionnaire__c pqRecordToUpdate = new Personal_Questionnaire__c();
        pqRecordToUpdate.Id = pq.Id;
        pqRecordToUpdate.Annual_Income_from_Employment__c = 10000;
        pqRecordToUpdate.Annual_Income_from_1099__c = 5000;
        update pqRecordToUpdate;
        
        //Get LOS_PQ_Income_Source_Automation_Setting__mdt Metadata Records
        Map<String, LOS_PQ_Income_Source_Automation_Setting__mdt> automationSettings = LOS_PQ_Income_Source_Automation_Setting__mdt.getAll();
        
        //Validation LOS_PQ_Income_Source_Automation_Setting__mdt Metadata Records
        Map<String, LOS_PQ_Income_Source_Automation_Setting__mdt> validAutomationSettings = LosPersonalQuestionnaireIncomeSource.validateAutomationSettings(automationSettings);
        
        //Get Personal Questionnaire Record after creation
        Personal_Questionnaire__c pqRecord = [SELECT Id, Primary_Income_Source__c,Secondary_Income_Source__c FROM Personal_Questionnaire__c WHERE Id = :pqRecordToUpdate.Id];
        
        /**
         * Validate Test Result
         * Expected: Primary_Income_Source__c = 'Annual_Income_from_Employment__c' Ref Code
         *           Secondary_Income_Source__c = 'Annual_Income_from_1099__c' Ref Code
         */
        
        //Assert Primary_Income_Source__c value on PQ Record
        System.assertEquals(validAutomationSettings.get('Annual_Income_from_Employment__c').Primary_Source_of_Income_Ref_Code__c,
        pqRecord.Primary_Income_Source__c,
        'Primary_Income_Source__c is not populated as expected On PQ Record. Please validate LOS_PQ_Income_Source_Automation_Setting__mdt custom metadata records and LosPersonalQuestionnaireIncomeSource class');
        
        //Assert Secondary_Income_Source__c value On PQ Record
        System.assertEquals(validAutomationSettings.get('Annual_Income_from_1099__c').Secondary_Source_of_Income_Ref_Code__c,
        pqRecord.Secondary_Income_Source__c,
        'Secondary_Income_Source__c is not populated as expected On PQ Record. Please validate LOS_PQ_Income_Source_Automation_Setting__mdt custom metadata records and LosPersonalQuestionnaireIncomeSource class'); 
    }

    @isTest
    static void unitTest3IncomeSourceAutomationOnPQUpdation(){
        //Create Application Record
        Application__c app = new Application__c();
        insert app;
        
        //Create Personal Questionnaire Record
        Personal_Questionnaire__c pq = new Personal_Questionnaire__c();
        pq.Name='Test';
        pq.Application__c=app.Id;
        insert pq;
        
        //Update Income Field on PQ Record on the same record as inserted above
        Personal_Questionnaire__c pqRecordToUpdate = new Personal_Questionnaire__c();
        pqRecordToUpdate.Id = pq.Id;
        pqRecordToUpdate.Annual_Income_from_Employment__c = 10000;
        pqRecordToUpdate.Annual_Income_from_1099__c = 5000;
        pqRecordToUpdate.Annual_Income_from_Pension__c = 5000;
        update pqRecordToUpdate;
        
        //Get LOS_PQ_Income_Source_Automation_Setting__mdt Metadata Records
        Map<String, LOS_PQ_Income_Source_Automation_Setting__mdt> automationSettings = LOS_PQ_Income_Source_Automation_Setting__mdt.getAll();
        
        //Validation LOS_PQ_Income_Source_Automation_Setting__mdt Metadata Records
        Map<String, LOS_PQ_Income_Source_Automation_Setting__mdt> validAutomationSettings = LosPersonalQuestionnaireIncomeSource.validateAutomationSettings(automationSettings);
        
        //Get Personal Questionnaire Record after creation
        Personal_Questionnaire__c pqRecord = [SELECT Id, Primary_Income_Source__c,Secondary_Income_Source__c FROM Personal_Questionnaire__c WHERE Id = :pqRecordToUpdate.Id];
        
        /**
         * Validate Test Result
         * Expected: Primary_Income_Source__c = 'Annual_Income_from_Employment__c' Ref Code
         *           Secondary_Income_Source__c = 'Annual_Income_from_1099__c' Ref Code
         */
        
        //Assert Primary_Income_Source__c value on PQ Record
        System.assertEquals(validAutomationSettings.get('Annual_Income_from_Employment__c').Primary_Source_of_Income_Ref_Code__c,
        pqRecord.Primary_Income_Source__c,
        'Primary_Income_Source__c is not populated as expected On PQ Record. Please validate LOS_PQ_Income_Source_Automation_Setting__mdt custom metadata records and LosPersonalQuestionnaireIncomeSource class');
        
        //Assert Secondary_Income_Source__c value On PQ Record
        System.assertEquals(validAutomationSettings.get('Annual_Income_from_1099__c').Secondary_Source_of_Income_Ref_Code__c,
        pqRecord.Secondary_Income_Source__c,
        'Secondary_Income_Source__c is not populated as expected On PQ Record. Please validate LOS_PQ_Income_Source_Automation_Setting__mdt custom metadata records and LosPersonalQuestionnaireIncomeSource class'); 
    }
}