force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Fraud_Flag__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Flag__c</fullName>
    <label>Fraud Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application Submission</fullName>
            </value>
            <value>
                <fullName>Documentation Verification</fullName>
            </value>
            <value>
                <fullName>Credit Evaluation</fullName>
            </value>
            <value>
                <fullName>Loan Underwriting</fullName>
            </value>
            <value>
                <fullName>Loan Approval and Disbursement</fullName>
            </value>
            <value>
                <fullName>Loan Servicing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_Reason__c/Status_Reason__c.object-meta.xml
<CustomObject>
    <label>Status Reason</label>
    <nameField>
        <label>Status Reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_Reason__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Status Reasons</relationshipLabel>
    <relationshipName>Status_Reasons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApplicationTriggerHandler.cls
public class ApplicationTriggerHandler {
    public static void deleteStatusReasonOnFlagReset(List<Application__c> newList, Map<Id,Application__c> oldMap){
        Set<Id> appIds = new Set<Id>();
        Map<Id,String> mapOfApplicationStage = new Map<Id,String>();
        
        for(Application__c app:newList){
            if(app.Fraud_Flag__c == 'No' && app.Fraud_Flag__c != oldMap.get(app.Id).Fraud_Flag__c && app.Status__c=='Declined'){
               appIds.add(app.Id);
               mapOfApplicationStage.put(app.Id,app.Stage__c);
            }
        }
        
        if(!appIds.isEmpty()){
            List<Status_Reason__c> statusReasonList = [Select Id,Stage__c,Status__c,Application__c from Status_Reason__c where name ='Unable to verify'  and Application__c In : appIds];
            if(statusReasonList!=null){
                List<Status_Reason__c> statusReasonToDelete = new List<Status_Reason__c>();
                for(Status_Reason__c sr : statusReasonList){
                    if(sr.Stage__c == mapOfApplicationStage.get(sr.Application__c)){
                        statusReasonToDelete.add(sr);
                    }
                }
                if(!statusReasonToDelete.isEmpty()){
                    delete statusReasonToDelete;
                }
            }
           
        }
        
    }
}