force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Primary_Income_Source__c.field-meta.xml
<CustomField>
    <fullName>Primary_Income_Source__c</fullName>
    <formula>&apos;7&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Income Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/Personal_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Personal Questionnaire</label>
    <nameField>
        <label>Personal Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Alimony_Amount__c.field-meta.xml
<CustomField>
    <fullName>Alimony_Amount__c</fullName>
    <label>Alimony Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Amount_2__c.field-meta.xml
<CustomField>
    <fullName>Amount_2__c</fullName>
    <label>Amount 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Annual_Income_from_1099__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income_from_1099__c</fullName>
    <label>Self-Employed, Contracted or Freelance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Annual_Income_from_Employment__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income_from_Employment__c</fullName>
    <label>Employment Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Annual_Income_from_Pension__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income_from_Pension__c</fullName>
    <label>Pension</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Personal Questionnaires</relationshipLabel>
    <relationshipName>Personal_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Chk_to_PL__c.field-meta.xml
<CustomField>
    <fullName>Chk_to_PL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chk to PL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Primary_Income_Source__c.field-meta.xml
<CustomField>
    <fullName>Primary_Income_Source__c</fullName>
    <label>Primary Income Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_Of_Income</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Receive_Amount__c.field-meta.xml
<CustomField>
    <fullName>Receive_Amount__c</fullName>
    <label>Receive Amount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Secondary_Income_Source__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Income_Source__c</fullName>
    <label>Secondary Income Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_Of_Income</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Amount__c + Amount_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ApexController.cls
public class ApexController {

    @AuraEnabled(cacheable = true)
    public static List<Personal_Questionnaire__c> getSamplePQData(){
        return [SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, 
                LastModifiedDate, LastModifiedById, SystemModstamp, LastViewedDate, 
                LastReferencedDate, Amount__c, Receive_Amount__c, Amount_2__c, 
                Total_Amount__c, Primary_Income_Source__c, Alimony_Amount__c, 
                Number__c, Secondary_Income_Source__c, Annual_Income_from_Employment__c, 
                Annual_Income_from_1099__c, Annual_Income_from_Pension__c, Other_Income__c, 
                Application__c,Application__r.Name, Chk_to_PL__c FROM Personal_Questionnaire__c ];
    }

    @AuraEnabled(cacheable = true)
    public static List<Personal_Questionnaire__c> getSamplePQData2(){
        return [SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, 
                LastModifiedDate, LastModifiedById, SystemModstamp, LastViewedDate, 
                LastReferencedDate, Amount__c, Receive_Amount__c, Amount_2__c, 
                Annual_Income_from_1099__c, Annual_Income_from_Pension__c, Other_Income__c, 
                Application__c,Application__r.Name, Chk_to_PL__c FROM Personal_Questionnaire__c ];
    }

    @AuraEnabled(cacheable = true)
    public static List<Opportunity> getSampleOpportunityData(){
        return [Select Id,StageName, AccountId,Account.Name,CreatedDate,LastModifiedDate from Opportunity  ];
    }
    @AuraEnabled(cacheable = true)
    public static List<Account> getSampleAccountData(){
        return [Select Id,Name,Phone,AccountNumber,CreatedDate,LastModifiedDate from Account];
    }

    @AuraEnabled(cacheable = true)
    public static List<Contact> getSampleContactData(){
        return [Select Id,Name,Email,AccountId,Account.Name from Contact ];
    }
    
}