force-app/main/default/objects/Personal_Questionnaire__c/Personal_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Personal Questionnaire</label>
    <nameField>
        <label>Personal Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Chk_to_PL__c.field-meta.xml
<CustomField>
    <fullName>Chk_to_PL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chk to PL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Personal_Questionnaire__c/fields/Receive_Amount__c.field-meta.xml
<CustomField>
    <fullName>Receive_Amount__c</fullName>
    <label>Receive Amount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InformationFormController.cls
/**
* @File Name : InformationFormController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : February 28, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | February 28, 2025 |   | Initial Version
**/

public class InformationFormController {

	public class InformationWrapper{
		@AuraEnabled public String personalQuesId;
		@AuraEnabled public Personal_Questionnaire__c personalQues;
		@AuraEnabled public String savedMessage;
	}
	@AuraEnabled
	public static InformationWrapper getInformation(String personalQuesId){
		List<Personal_Questionnaire__c> personalQuesList =  [Select Id,Name,Receive_Amount__c,Amount__c,Chk_to_PL__c from Personal_Questionnaire__c  where Id = :personalQuesId];
		if(!personalQuesList.isEmpty()){
			InformationWrapper iw = new InformationWrapper();
			iw.personalQues = personalQuesList[0];
			return iw;
		}
		else{
			return null;
		}
	}
	@AuraEnabled
	public static InformationWrapper saveInformation(String informationWrapper){
		InformationWrapper iw = (InformationWrapper)JSON.deserialize(informationWrapper, InformationWrapper.class);
		update iw.personalQues;
		iw.savedMessage = 'Success';
		return iw;
	}

}