force-app/main/default/objects/User_Access_Request__c/User_Access_Request__c.object-meta.xml
<CustomObject>
    <label>User Access Request</label>
    <nameField>
        <displayFormat>UAR-{0000000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Access_Request__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Request__c/fields/Provision_Type__c.field-meta.xml
<CustomField>
    <fullName>Provision_Type__c</fullName>
    <label>Provision Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ad-Hoc</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Immediate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Request__c/fields/Recurs_every_on__c.field-meta.xml
<CustomField>
    <fullName>Recurs_every_on__c</fullName>
    <label>Recurs every  on</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activate User</fullName>
            </value>
            <value>
                <fullName>Deactivate User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UserAccessRequest.cls
public class UserAccessRequest {
    public static void grantAccess(){
        List<User_Access_Request__c >  requestList= [Select Id,Start_Date__c,End_Date__c,Provision_Type__c,Request_Type__c,Frequency__c,Recurs_every_on__c from User_Access_Request__c where Start_Date__c <=TODAY and End_Date__c >=TODAY and Is_Active__c =false ];
        for(User_Access_Request__c request:requestList){
            if(request.Provision_Type__c=='Ad-Hoc' && request.Request_Type__c=='Activate User'){
                //Add user to activate list
            }
            else if(request.Provision_Type__c=='Ad-Hoc' && request.Request_Type__c=='Deactivate User'){
                // Add user to deactivate list
            }
            else if(request.Provision_Type__c=='Recurring' && request.Request_Type__c=='Activate User' && recurringRequestNeedsGrant(request)){
                System.debug('grant reurring access');
            }
        }
    }
    
    private static Boolean recurringRequestNeedsGrant(User_Access_Request__c request){
        // Check for weekly
        if(request.Frequency__c!=null && request.Frequency__c=='Weekly'){
            List<String> listOfWeekdays = request.Recurs_every_on__c.split(';');
            String dayoftheWeek = dayOfTheWeek(System.today());
            for(String weekday:listOfWeekdays){
                if(weekday==dayoftheWeek){
                    return true;
                }
            }
            return false;
            
        }
        else if(request.Frequency__c!=null && request.Frequency__c=='Monthly'){
            
        }
        return false;
    }
	
    private static String dayOfTheWeek(Date inputDate){
        Datetime inputDateTime = (DateTime)inputDate;
        String dayOfWeek = inputDateTime.format('EEEE');
        return dayOfWeek;
    }
    private static Integer dayOfTheMonth(Date inputDate){
       return inputDate.day();
    }
	    
}